// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdngunznxouvwvqgewmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbmd1bnpueG91dnd2cWdld216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MDcyOTAsImV4cCI6MjA1MjA4MzI5MH0.ckxjcqpYFH38YeqrKCAGKPb7IWOmwE40cP_GE-ArdFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);